package com.jora.billing.common;

public class ImagesMainScreen {
	private static final String mainScreenIcons = "images/mainScreenLogoEnabled/";

	private static final String mainScreenIconshover = "images/mainScreenLogoHover/";

	private static final String mainScreenIconsdisable = "images/mainScreenLogoDisabled/";

	private static final String iconpath = "images/icons/";

	public enum Images {
		IMAGE_MENU_RIGHTS("images/mainScreenLogoEnabled/MenuRights.svg"),
		IMAGE_MENU_RIGHTS_HOVER("images/mainScreenLogoHover/MenuRights.svg"),
		IMAGE_MENU_RIGHTS_DISABLE("images/mainScreenLogoDisabled/MenuRights.svg"),
		IMAGE_OPERATOR("images/mainScreenLogoEnabled/OperatorEntry.svg"),
		IMAGE_OPERATOR_HOVER("images/mainScreenLogoHover/OperatorEntry.svg"),
		IMAGE_OPERATOR_DISABLE("images/mainScreenLogoDisabled/OperatorEntry.svg"),
		IMAGE_OPERATOR_BRANCH_ASSIGN("images/mainScreenLogoEnabled/OperatorBranchAssign.svg"),
		IMAGE_OPERATOR_BRANCH_ASSIGN_HOVER("images/mainScreenLogoHover/OperatorBranchAssign.svg"),
		IMAGE_OPERATOR_BRANCH_ASSIGN_DISABLE("images/mainScreenLogoDisabled/OperatorBranchAssign.svg"),
		IMAGE_HSN("images/mainScreenLogoEnabled/HSNMaster.svg"),
		IMAGE_HSN_HOVER("images/mainScreenLogoHover/HSNMaster.svg"),
		IMAGE_HSN_DISABLE("images/mainScreenLogoDisabled/HSNMaster.svg"),
		IMAGE_TAX_MASTER("images/mainScreenLogoEnabled/TaxMaster.svg"),
		IMAGE_TAX_MASTER_hover("images/mainScreenLogoHover/TaxMaster.svg"),
		IMAGE_TAX_MASTER_DISABLE("images/mainScreenLogoDisabled/TaxMaster.svg"),
		IMAGE_BALGROUP("images/mainScreenLogoEnabled/BalanceGroup.svg"),
		IMAGE_BALGROUP_HOVER("images/mainScreenLogoHover/BalanceGroup.svg"),
		IMAGE_BALGROUP_DISABLE("images/mainScreenLogoDisabled/BalanceGroup.svg"),
		IMAGE_APPROVAL_ENTRY("images/mainScreenLogoEnabled/ApprovalEntry.svg"),
		IMAGE_APPROVAL_ENTRY_HOVER("images/mainScreenLogoHover/ApprovalEntry.svg"),
		IMAGE_APPROVAL_ENTRY_DISABLE("images/mainScreenLogoDisabled/ApprovalEntry.svg"),
		IMAGE_APPROVAL_RECEIPT("images/mainScreenLogoEnabled/ApprovalReceipt.svg"),
		IMAGE_APPROVAL_RECEIPT_HOVER("images/mainScreenLogoHover/ApprovalReceipt.svg"),
		IMAGE_APPROVAL_RECEIPT_DISABLE("images/mainScreenLogoDisabled/ApprovalReceipt.svg"),
		IMAGE_DUPLICATE_TAG("images/mainScreenLogoEnabled/DuplicateTag.svg"),
		IMAGE_DUPLICATE_TAG_HOVER("images/mainScreenLogoHover/DuplicateTag.svg"),
		IMAGE_DUPLICATE_TAG_DISABLE("images/mainScreenLogoDisabled/DuplicateTag.svg"),
		IMAGE_ADVANCE_ENTRY("images/mainScreenLogoEnabled/AdvanceEntry.svg"),
		IMAGE_ADVANCE_ENTRY_HOVER("images/mainScreenLogoHover/AdvanceEntry.svg"),
		IMAGE_ADVANCE_ENTRY_DISABLE("images/mainScreenLogoDisabled/AdvanceEntry.svg"),
		IMAGE_COUNTER_CHANGE("images/mainScreenLogoEnabled/CounterIssue.svg"),
		IMAGE_COUNTER_CHANGE_HOVER("images/mainScreenLogoHover/CounterIssue.svg"),
		IMAGE_COUNTER_CHANGE_DISABLE("images/mainScreenLogoDisabled/CounterIssue.svg"),
		IMAGE_COUNTER_MASTER("images/mainScreenLogoEnabled/CounterMaster.svg"),
		IMAGE_COUNTER_MASTER_HOVER("images/mainScreenLogoHover/CounterMaster.svg"),
		IMAGE_COUNTER_MASTER_DISABLE("images/mainScreenLogoDisabled/CounterMaster.svg"),
		IMAGE_OTHERISSUE("images/mainScreenLogoEnabled/OtherIssue.svg"),
		IMAGE_OTHERISSUE_HOVER("images/mainScreenLogoHover/OtherIssue.svg"),
		IMAGE_OTHERISSUE_DISABLE("images/mainScreenLogoDisabled/OtherIssue.svg"),
		IMAGE_BAL_SUB_GROUP("images/mainScreenLogoEnabled/BalanceSubgroup.svg"),
		IMAGE_BAL_SUB_GROUP_HOVER("images/mainScreenLogoHover/BalanceSubgroup.svg"),
		IMAGE_BAL_SUB_GROUP_DISABLE("images/mainScreenLogoDisabled/BalanceSubgroup.svg"),
		IMAGE_ACCOUNTS_HEAD("images/mainScreenLogoEnabled/accounts-head.svg"),
		IMAGE_ACCOUNTS_HEAD_HOVER("images/mainScreenLogoHover/accounts-head.svg"),
		IMAGE_ACCOUNTS_HEAD_DISABLE("images/mainScreenLogoDisabled/accounts-head.svg"),
		IMAGE_VENDORTERMS("images/mainScreenLogoEnabled/VendorTC.svg"),
		IMAGE_VENDORTERMS_HOVER("images/mainScreenLogoHover/VendorTC.svg"),
		IMAGE_VENDORTERMS_DISABLE("images/mainScreenLogoDisabled/VendorTC.svg"),
		IMAGE_CITYMASTER("images/mainScreenLogoEnabled/CityMaster.svg"),
		IMAGE_CITYMASTER_HOVER("images/mainScreenLogoHover/CityMaster.svg"),
		IMAGE_CITYMASTER_DISABLE("images/mainScreenLogoDisabled/CityMaster.svg"),
		IMAGE_INTEGRATION("images/mainScreenLogoEnabled/IntegrationMaster.svg"),
		IMAGE_INTEGRATION_HOVER("images/mainScreenLogoHover/IntegrationMaster.svg"),
		IMAGE_INTEGRATION_DISABLE("images/mainScreenLogoDisabled/IntegrationMaster.svg"),
		IMAGE_JEWEL_PRODUCT("images/mainScreenLogoEnabled/Jewelproduct.svg"),
		IMAGE_JEWEL_PRODUCT_HOVER("images/mainScreenLogoHover/Jewelproduct.svg"),
		IMAGE_JEWEL_PRODUCT_DISABLE("images/mainScreenLogoDisabled/Jewelproduct.svg"),
		IMAGE_PRINTER_CONTROL("images/mainScreenLogoEnabled/PrintControl.svg"),
		IMAGE_PRINTER_CONTROL_HOVER("images/mainScreenLogoHover/PrintControl.svg"),
		IMAGE_PRINTER_CONTROL_DISABLE("images/mainScreenLogoDisabled/PrintControl.svg"),
		IMAGE_PRINTER_MASTER("images/mainScreenLogoEnabled/PrintMaster.svg"),
		IMAGE_PRINTER_MASTER_HOVER("images/mainScreenLogoHover/PrintMaster.svg"),
		IMAGE_PRINTER_MASTER_DISABLE("images/mainScreenLogoDisabled/PrintMaster.svg"),
		IMAGE_CATEGORY_MASTER("images/mainScreenLogoEnabled/CategoryMaster.svg"),
		IMAGE_CATEGORY_MASTER_HOVER("images/mainScreenLogoHover/CategoryMaster.svg"),
		IMAGE_CATEGORY_MASTER_DISABLE("images/mainScreenLogoDisabled/CategoryMaster.svg"),
		IMAGE_SUBPODUCT_MASTER("images/mainScreenLogoEnabled/SubProductMaster.svg"),
		IMAGE_SUBPODUCT_MASTER_HOVER("images/mainScreenLogoHover/SubProductMaster.svg"),
		IMAGE_SUBPODUCT_MASTER_DISABLE("images/mainScreenLogoDisabled/SubProductMaster.svg"),
		IMAGE_PRODUCT("images/mainScreenLogoEnabled/ProductMaster.svg"),
		IMAGE_PRODUCT_HOVER("images/mainScreenLogoHover/ProductMaster.svg"),
		IMAGE_PRODUCT_DISABLE("images/mainScreenLogoDisabled/ProductMaster.svg"),
		IMAGE_SIZE_MASTER("images/mainScreenLogoEnabled/SizeMaster.svg"),
		IMAGE_SIZE_MASTER_HOVER("images/mainScreenLogoHover/SizeMaster.svg"),
		IMAGE_SIZE_MASTER_DISABLE("images/mainScreenLogoDisabled/SizeMaster.svg"),
		IMAGE_MODAL_MASTER("images/mainScreenLogoEnabled/ModelMaster.svg"),
		IMAGE_MODAL_MASTER_HOVER("images/mainScreenLogoHover/ModelMaster.svg"),
		IMAGE_MODAL_MASTER_DISABLE("images/mainScreenLogoDisabled/ModelMaster.svg"),
		IMAGE_MODAL_LINK("images/mainScreenLogoEnabled/ModalMasterLink.svg"),
		IMAGE_MODAL_LINK_HOVER("images/mainScreenLogoHover/ModalMasterLink.svg"),
		IMAGE_MODAL_LINK_DISABLE("images/mainScreenLogoDisabled/ModalMasterLink.svg"),
		IMAGE_OPENINGENTRY("images/mainScreenLogoEnabled/OpeningEntry.svg"),
		IMAGE_OPENINGENTRY_HOVER("images/mainScreenLogoHover/OpeningEntry.svg"),
		IMAGE_OPENINGENTRY_DISABLE("images/mainScreenLogoDisabled/OpeningEntry.svg"),
		IMAGE_MODULE_RIGHTS("images/mainScreenLogoEnabled/ModuleRights.svg"),
		IMAGE_MODULE_RIGHTS_HOVER("images/mainScreenLogoHover/ModuleRights.svg"),
		IMAGE_MODULE_RIGHTS_DISABLE("images/mainScreenLogoDisabled/ModuleRights.svg"),
		IMAGE_TAG_SCAN_INPUT("images/mainScreenLogoEnabled/InputTagTransfer.svg"),
		IMAGE_TAG_SCAN_INPUT_HOVER("images/mainScreenLogoHover/InputTagTransfer.svg"),
		IMAGE_TAG_SCAN_INPUT_DISABLE("images/mainScreenLogoDisabled/InputTagTransfer.svg"),
		IMAGE_SIZE_LINK("images/mainScreenLogoEnabled/SizeLink.svg"),
		IMAGE_SIZE_LINK_HOVER("images/mainScreenLogoHover/SizeLink.svg"),
		IMAGE_SIZE_LINK_DISABLE("images/mainScreenLogoDisabled/SizeLink.svg"),
		ICON_COMPCODE("images/icons/Comapany-code.svg"), ICON_COMPYDB("images/icons/Compydb.svg"),
		ICON_FILEMAIN("images/icons/filemain.svg"), ICON_IPADDRESS("images/icons/ip-addres.svg"),
		ICON_USER("images/icons/User.svg"), ICON_VERSION("images/icons/Version.svg"),
		IMAGE_PURCHASE_ENTRY("images/mainScreenLogoEnabled/PurchaseEntry.svg"),
		IMAGE_PURCHASE_ENTRY_HOVER("images/mainScreenLogoHover/PurchaseEntry.svg"),
		IMAGE_PURCHASE_ENTRY_DISABLE("images/mainScreenLogoDisabled/PurchaseEntry.svg"),
		IMAGE_PURCHASE_RETURN("images/mainScreenLogoEnabled/PurchaseReturn.svg"),
		IMAGE_PURCHASE_RETURN_hover("images/mainScreenLogoHover/PurchaseReturn.svg"),
		IMAGE_PURCHASE_RETURN_Disable("images/mainScreenLogoDisabled/PurchaseReturn.svg"),
		IMAGE_DEPARTMENT_TRANSFER("images/mainScreenLogoEnabled/DepartmentTransfer.svg"),
		IMAGE_DEPARTMENT_TRANSFER_HOVER("images/mainScreenLogoHover/DepartmentTransfer.svg"),
		IMAGE_DEPARTMENT_TRANSFER_DISABLE("images/mainScreenLogoDisabled/DepartmentTransfer.svg"),
		IMAGE_LOTTO_DEPARTMENT_TRANSFER("images/mainScreenLogoEnabled/lot-dpt-transfer.svg"),
		IMAGE_LOTTO_DEPARTMENT_TRANSFER_HOVER("images/mainScreenLogoHover/lot-dpt-transfer.svg"),
		IMAGE_LOTTO_DEPARTMENT_TRANSFER_DISABLE("images/mainScreenLogoDisabled/lot-dpt-transfer.svg"),
		IMAGE_SINGLE_TAG_ENTRY("images/mainScreenLogoEnabled/SingleTagGeneration.svg"),
		IMAGE_SINGLE_TAG_ENTRY_HOVER("images/mainScreenLogoHover/SingleTagGeneration.svg"),
		IMAGE_SINGLE_TAG_ENTRY_DISABLE("images/mainScreenLogoDisabled/SingleTagGeneration.svg"),
		IMAGE_BULK_TAG_ENTRY("images/mainScreenLogoEnabled/BulkTagGeneration.svg"),
		IMAGE_BULK_TAG_ENTRY_HOVER("images/mainScreenLogoHover/BulkTagGeneration.svg"),
		IMAGE_BULK_TAG_ENTRY_DISABLE("images/mainScreenLogoDisabled/BulkTagGeneration.svg"),
		IMAGE_ISSUE("images/mainScreenLogoEnabled/IssueEntry.svg"),
		IMAGE_ISSUE_HOVER("images/mainScreenLogoHover/IssueEntry.svg"),
		IMAGE_ISSUE_DISABLE("images/mainScreenLogoDisabled/IssueEntry.svg"),
		IMAGE_RETURN("images/mainScreenLogoEnabled/ReturnEntry.svg"),
		IMAGE_RETURN_HOVER("images/mainScreenLogoHover/ReturnEntry.svg"),
		IMAGE_RETURN_DISABLE("images/mainScreenLogoDisabled/ReturnEntry.svg"),
		IMAGE_PURCHASE_ORDER("images/mainScreenLogoEnabled/PurchaseOrder.svg"),
		IMAGE_PURCHASE_ORDER_hover("images/mainScreenLogoHover/PurchaseOrder.svg"),
		IMAGE_PURCHASE_ORDER_DISABLE("images/mainScreenLogoDisabled/PurchaseOrder.svg"),
		IMAGE_TAG_SCANNING("images/mainScreenLogoEnabled/TagScanningBranchTransfer.svg"),
		IMAGE_TAG_SCANNING_HOVER("images/mainScreenLogoHover/TagScanningBranchTransfer.svg"),
		IMAGE_TAG_SCANNING_DISABLE("images/mainScreenLogoDisabled/TagScanningBranchTransfer.svg"),
		IMAGE_PURCHASE_REPORT("images/mainScreenLogoEnabled/PurchaseReport.svg"),
		IMAGE_PURCHASE_REPORT_HOVER("images/mainScreenLogoHover/PurchaseReport.svg"),
		IMAGE_PURCHASE_REPORT_DISABLE("images/mainScreenLogoDisabled/PurchaseReport.svg"),
		IMAGE_BRANCH_TRANSFER_REPORT("images/mainScreenLogoEnabled/BranchTranReport.svg"),
		IMAGE_BRANCH_TRANSFER_REPORT_HOVER("images/mainScreenLogoHover/BranchTranReport.svg"),
		IMAGE_BRANCH_TRANSFER_REPORT_DISABLE("images/mainScreenLogoDisabled/BranchTranReport.svg"),
		IMAGE_PRODUCT_WISE_STOCK_REPORT("images/mainScreenLogoEnabled/StockReport.svg"),
		IMAGE_PRODUCT_WISE_STOCK_REPORT_HOVER("images/mainScreenLogoHover/StockReport.svg"),
		IMAGE_PRODUCT_WISE_STOCK_REPORT_DISABLE("images/mainScreenLogoDisabled/StockReport.svg"),
		IMAGE_ORDER_WISE_REPORT("images/mainScreenLogoEnabled/Orderwise"),
		IMAGE_ORDER_WISE_REPORT_HOVER("images/mainScreenLogoHover/Orderwise"),
		IMAGE_ORDER_WISE_REPORT_DISABLE("images/mainScreenLogoDisabled/Orderwise"),
		IMAGE_BRANCH_STOCK_REQUEST("images/mainScreenLogoEnabled/BTStockRequest.svg"),
		IMAGE_BRANCH_STOCK_REQUEST_HOVER("images/mainScreenLogoHover/BTStockRequest.svg"),
		IMAGE_BRANCH_STOCK_REQUEST_DISABLE("images/mainScreenLogoDisabled/BTStockRequest.svg"),
		IMAGE_DAYLOCK("images/mainScreenLogoEnabled/DayLock.svg"),
		IMAGE_DAYLOCK_HOVER("images/mainScreenLogoHover/DayLock.svg"),
		IMAGE_DAYLOCK_DISABLE("images/mainScreenLogoDisabled/DayLock.svg"),
		IMAGE_MULCONTROL("images/mainScreenLogoEnabled/MulControl.svg"),
		IMAGE_MULCONTROL_HOVER("images/mainScreenLogoHover/MulControl.svg"),
		IMAGE_MULCONTROL_DISABLE("images/mainScreenLogoDisabled/MulControl.svg"),
		IMAGE_CARTONNO_GENERATE("images/mainScreenLogoEnabled/CartonNoGenerate.svg"),
		IMAGE_CARTONNO_GENERATE_HOVER("images/mainScreenLogoHover/CartonNoGenerate.svg"),
		IMAGE_CARTONNO_GENERATE_DISABLE("images/mainScreenLogoDisabled/CartonNoGenerate.svg"),
		IMAGE_DEPT_TRAN_VIEW("images/mainScreenLogoEnabled/DeptTranView.svg"),
		IMAGE_DEPT_TRAN_VIEW_HOVER("images/mainScreenLogoHover/DeptTranView.svg"),
		IMAGE_DEPT_TRAN_VIEW_DISABLE("images/mainScreenLogoDisabled/DeptTranView.svg"),
		IMAGE_TRANS_CHECK_LIST("images/mainScreenLogoEnabled/TransCheckList.svg"),
		IMAGE_TRANS_CHECK_LIST_HOVER("images/mainScreenLogoHover/TransCheckList.svg"),
		IMAGE_TRANS_CHECK_LIST_DISABLE("images/mainScreenLogoDisabled/TransCheckList.svg"),
		IMAGE_PUR_DETAIL_REPORT("images/mainScreenLogoEnabled/perdetailsreport.svg"),
		IMAGE_PUR_DETAIL_REPORT_HOVER("images/mainScreenLogoHover/perdetailsreport.svg"),
		IMAGE_PUR_DETAIL_REPORT_DISABLE("images/mainScreenLogoDisabled/perdetailsreport.svg"),
		IMAGE_BRANCH_TRANSFER("images/mainScreenLogoEnabled/AutoTransfer.svg"),
		IMAGE_BRANCH_TRANSFER_HOVER("images/mainScreenLogoHover/AutoTransfer.svg"),
		IMAGE_BRANCH_TRANSFER_DISABLE("images/mainScreenLogoDisabled/AutoTransfer.svg"),
		IMAGE_BRANCH_TRANSFER_APPROVAL("images/mainScreenLogoEnabled/BranchTranApproval.svg"),
		IMAGE_BRANCH_TRANSFER_APPROVAL_HOVER("images/mainScreenLogoHover/BranchTranApproval.svg"),
		IMAGE_BRANCH_TRANSFER_APPROVAL_DISABLE("images/mainScreenLogoDisabled/BranchTranApproval.svg"),
		IMAGE_TRANSFER_SETTINGS("images/mainScreenLogoEnabled/TransferSettings.svg"),
		IMAGE_TRANSFER_SETTINGS_HOVER("images/mainScreenLogoHover/TransferSettings.svg"),
		IMAGE_TRANSFER_SETTINGS_DISABLE("images/mainScreenLogoDisabled/TransferSettings.svg"),
		IMAGE_STOCK_DOWNLOAD("images/mainScreenLogoEnabled/StockDownload.svg"),
		IMAGE_STOCK_DOWNLOAD_HOVER("images/mainScreenLogoHover/StockDownload.svg"),
		IMAGE_STOCK_DOWNLOAD_DISABLE("images/mainScreenLogoDisabled/StockDownload.svg"),
		IMAGE_SYNC_TRANSFER("images/mainScreenLogoEnabled/SyncTransfer.svg"),
		IMAGE_SYNC_TRANSFER_HOVER("images/mainScreenLogoHover/SyncTransfer.svg"),
		IMAGE_SYNC_TRANSFER_DISABLE("images/mainScreenLogoDisabled/SyncTransfer.svg"),
		IMAGE_VENDORRATELINK("images/mainScreenLogoEnabled/VendorRateLink.svg"),
		IMAGE_VENDORRATELINK_HOVER("images/mainScreenLogoHover/VendorRateLink.svg"),
		IMAGE_VENDORRATELINK_DISABLE("images/mainScreenLogoDisabled/VendorRateLink.svg"),
		IMAGE_PURCHASEVIEW("images/mainScreenLogoEnabled/PurchaseView.svg"),
		IMAGE_PURCHASEVIEW_HOVER("images/mainScreenLogoHover/PurchaseView.svg"),
		IMAGE_PURCHASEVIEW_DISABLE("images/mainScreenLogoDisabled/PurchaseView.svg"),
		IMAGE_VIEWANDCANCEL("images/mainScreenLogoEnabled/ViewAndCancel.svg"),
		IMAGE_VIEWANDCANCEL_HOVER("images/mainScreenLogoHover/ViewAndCancel.svg"),
		IMAGE_VIEWANDCANCEL_DISABLE("images/mainScreenLogoDisabled/ViewAndCancel.svg"),
		IMAGE_BT_APPROVAL_VIEW("images/mainScreenLogoEnabled/BTApprovalViewandCancel.svg"),
		IMAGE_BT_APPROVAL_VIEW_HOVER("images/mainScreenLogoHover/BTApprovalViewandCancel.svg"),
		IMAGE_BT_APPROVAL_VIEW_DISABLE("images/mainScreenLogoDisabled/BTApprovalViewandCancel.svg"),
		IMAGE_BT_VIEW("images/mainScreenLogoEnabled/BTViewandCancel.svg"),
		IMAGE_BT_VIEW_HOVER("images/mainScreenLogoHover/BTViewandCancel.svg"),
		IMAGE_BT_VIEW_DISABLE("images/mainScreenLogoDisabled/BTViewandCancel.svg"),
		IMAGE_PURCHASEORDERVIEW("images/mainScreenLogoEnabled/PurchaseOrderView.svg"),
		IMAGE_PURCHASEORDERVIEW_HOVER("images/mainScreenLogoHover/PurchaseOrderView.svg"),
		IMAGE_PURCHASEORDERVIEW_DISABLE("images/mainScreenLogoDisabled/PurchaseOrderView.svg"),
		IMAGE_JEWELLERYVSPACKINGMATERIALREPORT("images/mainScreenLogoEnabled/JewelleryVsPackingMaterialReport.svg"),
		IMAGE_JEWELLERYVSPACKINGMATERIALREPORT_HOVER("images/mainScreenLogoHover/JewelleryVsPackingMaterialReport.svg"),
		IMAGE_JEWELLERYVSPACKINGMATERIALREPORT_DISABLE(
				"images/mainScreenLogoDisabled/JewelleryVsPackingMaterialReport.svg"),
		IMAGE_COUNTERWISESTOCKREPORT("images/mainScreenLogoEnabled/CounterWiseStockReport.svg"),
		IMAGE_COUNTERWISESTOCKREPORT_HOVER("images/mainScreenLogoHover/CounterWiseStockReport.svg"),
		IMAGE_COUNTERWISESTOCKREPORT_DISABLE("images/mainScreenLogoDisabled/CounterWiseStockReport.svg"),
		IMAGE_BILLWISETRANSACTIONREPORT("images/mainScreenLogoEnabled/BillWiseTransactionReport.svg"),
		IMAGE_BILLWISETRANSACTIONREPORT_HOVER("images/mainScreenLogoHover/BillWiseTransactionReport.svg"),
		IMAGE_BILLWISETRANSACTIONREPORT_DISABLE("images/mainScreenLogoDisabled/BillWiseTransactionReport.svg"),
		IMAGE_SUBPRODUCTWISESTOCKREPORT("images/mainScreenLogoEnabled/SubProductWiseStockReport.svg"),
		IMAGE_SUBPRODUCTWISESTOCKREPORT_HOVER("images/mainScreenLogoHover/SubProductWiseStockReport.svg"),
		IMAGE_SUBPRODUCTWISESTOCKREPORT_DISABLE("images/mainScreenLogoDisabled/SubProductWiseStockReport.svg"),
		IMAGE_DEPARTMENTWISESTOCKREPORT("images/mainScreenLogoEnabled/DepartmentWiseStockReport.svg"),
		IMAGE_DEPARTMENTWISESTOCKREPORT_HOVER("images/mainScreenLogoHover/DepartmentWiseStockReport.svg"),
		IMAGE_DEPARTMENTWISESTOCKREPORT_DISABLE("images/mainScreenLogoDisabled/DepartmentWiseStockReport.svg"),
		COST_CENTRE("images/mainScreenLogoEnabled/CostCentre.svg"),
		COST_CENTRE_HOVER("images/mainScreenLogoHover/CostCentre.svg"),
		COST_CENTRE_DISABLE("images/mainScreenLogoDisabled/CostCentre.svg"),
		IMAGE_VERSION_UPGRADE("images/mainScreenLogoEnabled/VersionUpgrade.svg"),
		IMAGE_VERSION_UPGRADE_HOVER("images/mainScreenLogoHover/VersionUpgrade.svg"),
		IMAGE_VERSION_UPGRADE_DISABLE("images/mainScreenLogoDisabled/VersionUpgrade.svg"),
		IMAGE_CHANGE_YEAR("images/mainScreenLogoEnabled/ChangeYear.svg"),
		IMAGE_CHANGE_YEAR_HOVER("images/mainScreenLogoHover/ChangeYear.svg"),
		IMAGE_CHANGE_YEAR_DISABLE("images/mainScreenLogoDisabled/ChangeYear.svg"),
		IMAGE_DATA_CHECKLIST("images/mainScreenLogoEnabled/Datachecklist.svg"),
		IMAGE_DATA_CHECKLIST_HOVER("images/mainScreenLogoHover/Datachecklist.svg"),
		IMAGE_DATA_CHECKLIST_DISABLE("images/mainScreenLogoDisabled/Datachecklist.svg"),
		IMAGE_JEWEL_STOCK_ANALYSIS("images/mainScreenLogoEnabled/JewelStockAnalysis.svg"),
		IMAGE_JEWEL_STOCK_ANALYSIS_HOVER("images/mainScreenLogoHover/JewelStockAnalysis.svg"),
		IMAGE_JEWEL_STOCK_ANALYSIS_DISABLE("images/mainScreenLogoDisabled/JewelStockAnalysis.svg");

		private String value;

		Images(String value) {
			this.value = value;
		}

		public String getValue() {
			return this.value;
		}
	}

	public static String getMainscreenicons() {
		return mainScreenIcons;
	}

	public static String getMainscreeniconshover() {
		return mainScreenIconshover;
	}

	public static String getMainscreeniconsdisable() {
		return mainScreenIconsdisable;
	}

	public static String getIconpath() {
		return iconpath;
	}

}
